# fly.toml app configuration file generated for vernissage-api on 2023-11-09T17:58:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vernissage-api"
primary_region = "waw"
kill_signal = "SIGTERM"

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
[env]
  LOG_LEVEL = "info"
  VAPOR_ENV = "prod"
