name: Build
on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: '5.9'
    - name: Install libgd-dev
      run: brew install gd
    - name: Build
      run: swift build
    - name: Tests
      run: swift test
