name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install swift
      uses: YOCKOW/Action-setup-swift@v1
      with:
        swift-version: '5.8'
    - name: Build
      run: swift build
    - name: Tests
      run: swift test