name: Build Server

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: '5.10'
    - name: Install libgd-dev
      run: brew install gd
    - name: Build
      run: swift build
    - name: Tests
      run: swift test
