name: Build Server

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install swift
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: '6.0'
    - name: Update libraries
      run: apt-get -q update
    - name: Update distribution
      run: apt-get -q dist-upgrade -y
    - name: Install libraries
      run: sudo apt-get install -y libgd-dev libexif-dev libiptcdata0-dev
    - name: Build
      run: swift build
    - name: Tests
      run: swift test --no-parallel
