name: 'Close stale issues'
on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          any-of-labels: 'stale'
          days-before-stale: -1
          days-before-close: 7
          days-before-pr-close: -1
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'